### ISSUE TITLE
partial imports creates colouring bug

### ISSUE THREAD

**Issue by KevinBrogan** [aBothe/D-IDE#10]
number of characters after the colon is the number of characters that are highlighted in teal.

![image](https://f.cloud.github.com/assets/1428163/407102/34e3fed0-aade-11e2-906c-1d6d20ae8b44.png)
![image](https://f.cloud.github.com/assets/1428163/407105/7c1f3a44-aade-11e2-9980-55daf94fffae.png)
![image](https://f.cloud.github.com/assets/1428163/407106/8891a988-aade-11e2-922b-2d04e275c636.png)

**Comment by aBothe** [comment]
Fixed. Had to work on it a bit though. I hopefully can make it complete the specific modules' items sometime
