### ISSUE TITLE
dmd.exe not found

### ISSUE THREAD

**Issue by AlexanderBaggett** [aBothe/D-IDE#16]
Essentially I went to compile my program It did not show any errors, but said that dmd.exe was not found.  Now, the first time I went to install D-IDE it had me install D as well, and I did not do it in the default path the first time.

Nevertheless, I was able to use the dmd command at command prompt/cmd so I know it works in the PATH. But not for D-IDE.

But just to keep trying, I reinstalled D-IDE in its same location whilst reinstalling D in the default location. But this did not fix this issue either.
![cmd](https://f.cloud.github.com/assets/2896455/1818485/6ea89f24-7007-11e3-8394-c0204fa174d4.jpg)
![notfound](https://f.cloud.github.com/assets/2896455/1818486/6f60f97a-7007-11e3-9f35-d2533700e4b3.jpg)

**Comment by aBothe** [comment]
Just head to the options and fill in the dmd bin path - then it should work.

**Comment by AlexanderBaggett** [comment]
Ah, thank you.

**Comment by aBothe** [comment]
I updated the parser engine for D-IDE as well - now it's as fast/good as Mono-D again :)
