### ISSUE TITLE
Two errors when installing D-IDE on Windows 7 x64

### ISSUE THREAD

**Issue by linkerstorm** [aBothe/D-IDE#3]
Hi.

When I launch the "D-IDE2.web-install" on my Windows 7 x64 French OS, two errors appear close to the end of install.

I checked all the options but one : the DMD compiler which is already installed.

The first message box error is :

---

---

Error calling .NET DLL method

Impossible de trouver le fichier 'D:\x86\Developpement\D\D-IDE\䥄䕄䤮獮慴汬牥搮汬.dll'.
## OK   

The second message box error is :

---

---

Error calling .NET DLL method

Impossible de trouver le fichier 'D:\x86\Developpement\D\D-IDE\䥄䕄䤮獮慴汬牥搮汬.dll'.
## OK   

This two erros appear just after downloading during the install process.

The weird things here are the chinese chars, on my French OS !!!

Several tries lead to the same result.

Any suggestions welcome.

Regards.

EDIT : the consequences of this incomplete install is that D-IDE does not update automaticaly when starting, in spite of  the checked setting.

**Comment by aBothe** [comment]
Like I said already, I've had the same problem here, too, but I don't know the reason anymore. Anyway, let me try to install it on my own machine, and probably try to find a solution for this. Besides, have you installed the .Net framework (not only the client profile version!) and the VC++ runtime properly?

**Comment by linkerstorm** [comment]
Here my actual .NET framework 4 install :
- Microsoft .NET Framework 4 Client Profile
- Microsoft .NET Framework 4 Extended
- Microsoft .NET Framework 4 Multi-Targeting Pack

Do I missing a version ?

For VC++ :
- Microsoft Visual C++ 2005 ATL Update kb973923 - x64 8.0.50727.4053
- Microsoft Visual C++ 2005 Redistributable
- Microsoft Visual C++ 2005 Redistributable (x64)
- Microsoft Visual C++ 2005 Redistributable (x64) - KB2467175
- Microsoft Visual C++ 2008 Redistributable - KB2467174 - x64 9.0.30729.5570
- Microsoft Visual C++ 2008 Redistributable - KB2467174 - x86 9.0.30729.5570
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4974
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
- Microsoft Visual C++ 2010  x64 Redistributable - 10.0.30319
- Microsoft Visual C++ 2010  x64 Runtime - 10.0.40219
- Microsoft Visual C++ 2010  x86 Runtime - 10.0.40219

Do I miss a version ?

**Comment by aBothe** [comment]
I really can't imagine a reason for it anymore, sorry for that.

**Comment by linkerstorm** [comment]
Let me know if you found the bug, leaving a comment here, thanks.

**Comment by CyberShadow** [comment]
If you take "䥄䕄䤮獮慴汬牥搮汬", and save it in UCS-2 (UTF-16), and then view it in ASCII, you get "DIDE.Installer.dll".

Someone somewhere is appending an ASCII string to an Unicode string :)

**Comment by aBothe** [comment]
Honestly, I haven't touched the installer for longer than a year - I definitely don't know where to start to solve this problem - and due to the fact that just downloading the installer is fully sufficient (in theory), I don't really care about maintaining the nsis script anymore.. I mean, if there's someone who totally knows everything about how to fix it, please tell me or do it, but I don't want to spend time on fixing that anymore. Sorry about that.
Anyway, thanks for "translating" this confusing error message, Vlad :)

**Comment by CyberShadow** [comment]
I only tried it because the updater won't work for me ("The specified procedure could not be found."), but I suspect it's because something on my machine might be broken.

**Comment by aBothe** [comment]
I can ensure there's nothing broken on your machine - it's happening on my WinXP vm + win7 machine either .. probably it's got something to do with a not installed Visual Studio dll or something similar..I simply dunno (anymore) :/

**Comment by CyberShadow** [comment]
Ah, I just needed to run it elevated! What an odd error message, though.

**Comment by aBothe** [comment]
aahhh yeah, :D wow, it requires Admin rights...how intuitive xD
